// Code generated by MockGen. DO NOT EDIT.
// Source: login_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/akkinasrikar/ecommerce-cart/models"
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockLoginValidator is a mock of LoginValidator interface.
type MockLoginValidator struct {
	ctrl     *gomock.Controller
	recorder *MockLoginValidatorMockRecorder
}

// MockLoginValidatorMockRecorder is the mock recorder for MockLoginValidator.
type MockLoginValidatorMockRecorder struct {
	mock *MockLoginValidator
}

// NewMockLoginValidator creates a new mock instance.
func NewMockLoginValidator(ctrl *gomock.Controller) *MockLoginValidator {
	mock := &MockLoginValidator{ctrl: ctrl}
	mock.recorder = &MockLoginValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginValidator) EXPECT() *MockLoginValidatorMockRecorder {
	return m.recorder
}

// ValidateLogin mocks base method.
func (m *MockLoginValidator) ValidateLogin(ctx *gin.Context) (models.Login, models.EcomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateLogin", ctx)
	ret0, _ := ret[0].(models.Login)
	ret1, _ := ret[1].(models.EcomError)
	return ret0, ret1
}

// ValidateLogin indicates an expected call of ValidateLogin.
func (mr *MockLoginValidatorMockRecorder) ValidateLogin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateLogin", reflect.TypeOf((*MockLoginValidator)(nil).ValidateLogin), ctx)
}

// ValidateSignUp mocks base method.
func (m *MockLoginValidator) ValidateSignUp(ctx *gin.Context) (models.SignUp, models.EcomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSignUp", ctx)
	ret0, _ := ret[0].(models.SignUp)
	ret1, _ := ret[1].(models.EcomError)
	return ret0, ret1
}

// ValidateSignUp indicates an expected call of ValidateSignUp.
func (mr *MockLoginValidatorMockRecorder) ValidateSignUp(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSignUp", reflect.TypeOf((*MockLoginValidator)(nil).ValidateSignUp), ctx)
}
