// Code generated by MockGen. DO NOT EDIT.
// Source: repositories_gorm_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/akkinasrikar/ecommerce-cart/models"
	entities "github.com/akkinasrikar/ecommerce-cart/models/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateAddress mocks base method.
func (m *MockRepositoryInterface) CreateAddress(addressDetails entities.DeliveryAddress) (entities.DeliveryAddress, models.EcomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddress", addressDetails)
	ret0, _ := ret[0].(entities.DeliveryAddress)
	ret1, _ := ret[1].(models.EcomError)
	return ret0, ret1
}

// CreateAddress indicates an expected call of CreateAddress.
func (mr *MockRepositoryInterfaceMockRecorder) CreateAddress(addressDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddress", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateAddress), addressDetails)
}

// CreateCardDetails mocks base method.
func (m *MockRepositoryInterface) CreateCardDetails(cardDetails entities.CardDetails) (entities.CardDetails, models.EcomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCardDetails", cardDetails)
	ret0, _ := ret[0].(entities.CardDetails)
	ret1, _ := ret[1].(models.EcomError)
	return ret0, ret1
}

// CreateCardDetails indicates an expected call of CreateCardDetails.
func (mr *MockRepositoryInterfaceMockRecorder) CreateCardDetails(cardDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCardDetails", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateCardDetails), cardDetails)
}

// CreateEcomAccount mocks base method.
func (m *MockRepositoryInterface) CreateEcomAccount(ecomAccountDetails entities.EcomUsers) (entities.EcomUsers, models.EcomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEcomAccount", ecomAccountDetails)
	ret0, _ := ret[0].(entities.EcomUsers)
	ret1, _ := ret[1].(models.EcomError)
	return ret0, ret1
}

// CreateEcomAccount indicates an expected call of CreateEcomAccount.
func (mr *MockRepositoryInterfaceMockRecorder) CreateEcomAccount(ecomAccountDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEcomAccount", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateEcomAccount), ecomAccountDetails)
}

// GetAddress mocks base method.
func (m *MockRepositoryInterface) GetAddress(userDetails entities.EcomUsers) ([]entities.DeliveryAddress, models.EcomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddress", userDetails)
	ret0, _ := ret[0].([]entities.DeliveryAddress)
	ret1, _ := ret[1].(models.EcomError)
	return ret0, ret1
}

// GetAddress indicates an expected call of GetAddress.
func (mr *MockRepositoryInterfaceMockRecorder) GetAddress(userDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddress", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAddress), userDetails)
}

// GetAllProducts mocks base method.
func (m *MockRepositoryInterface) GetAllProducts() ([]entities.Item, models.EcomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts")
	ret0, _ := ret[0].([]entities.Item)
	ret1, _ := ret[1].(models.EcomError)
	return ret0, ret1
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockRepositoryInterfaceMockRecorder) GetAllProducts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAllProducts))
}

// GetCardDetails mocks base method.
func (m *MockRepositoryInterface) GetCardDetails(userDetails entities.EcomUsers) ([]entities.CardDetails, models.EcomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardDetails", userDetails)
	ret0, _ := ret[0].([]entities.CardDetails)
	ret1, _ := ret[1].(models.EcomError)
	return ret0, ret1
}

// GetCardDetails indicates an expected call of GetCardDetails.
func (mr *MockRepositoryInterfaceMockRecorder) GetCardDetails(userDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardDetails", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCardDetails), userDetails)
}

// GetUserDetails mocks base method.
func (m *MockRepositoryInterface) GetUserDetails(ctx context.Context) (entities.EcomUsers, models.EcomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDetails", ctx)
	ret0, _ := ret[0].(entities.EcomUsers)
	ret1, _ := ret[1].(models.EcomError)
	return ret0, ret1
}

// GetUserDetails indicates an expected call of GetUserDetails.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserDetails(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDetails", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserDetails), ctx)
}

// Login mocks base method.
func (m *MockRepositoryInterface) Login(userDetails entities.Login) (entities.SignUp, models.EcomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", userDetails)
	ret0, _ := ret[0].(entities.SignUp)
	ret1, _ := ret[1].(models.EcomError)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockRepositoryInterfaceMockRecorder) Login(userDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockRepositoryInterface)(nil).Login), userDetails)
}

// SignUp mocks base method.
func (m *MockRepositoryInterface) SignUp(userDetails entities.SignUp) (entities.SignUp, models.EcomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", userDetails)
	ret0, _ := ret[0].(entities.SignUp)
	ret1, _ := ret[1].(models.EcomError)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockRepositoryInterfaceMockRecorder) SignUp(userDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockRepositoryInterface)(nil).SignUp), userDetails)
}
